job.type: train
dataset.name: fb15k-237

model: reciprocal_relations_context_model
reciprocal_relations_context_model.base_model.type: hitter # redundant since also default
reciprocal_relations_context_model.neighborhood_size: 50
reciprocal_relations_context_model.base_model.neighborhood_size: 0
reciprocal_relations_context_model.base_model.encoder.dropout: 0.1

train:
  batch_size: 512
  loss_arg: .nan
  lr_warmup: 30
  lr_scheduler: LinearLR
  lr_scheduler_args:
    start_factor: 1
    end_factor: 0
    total_iters: 270
  max_epochs: 300
  optimizer: Adamax
  optimizer_args:
    lr: 0.01
    eps: 1e-6
    weight_decay: 0.01
  type: 1vsAllMaskedEntityPrediction

valid:
  early_stopping:
    patience: 10
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test

lookup_embedder:
  dim: 320
  initialize: normal_
  initialize_args:
    normal_:
      std: 0.02
  dropout: 0.

#conve:
#  feature_map_dropout: 0.48769345636955713
#  projection_dropout: 0.5
#  relation_embedder:
#    dropout: 0.11757230155305998
#    regularize_weight: 2.231687936571624e-14
#  round_dim: true

1vsAllMaskedEntityPrediction:
  entity_prediction_fraction: 0.
  entity_prediction_fraction_replaced: 0.1
  entity_prediction_fraction_unchanged: 0.1
  scoring_fraction_replaced: 0.
  scoring_fraction_unchanged: 0.5
